steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/group-dots-ui/group-dots-ui:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/group-dots-ui/group-dots-ui:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'group-dots-ui', '--image', 'gcr.io/$PROJECT_ID/group-dots-ui/group-dots-ui:latest', '--region', 'us-west2']
images:
  - gcr.io/$PROJECT_ID/group-dots-ui/group-dots-ui:latest
