steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/group-dots-ui/group-dots-ui:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/group-dots-ui/group-dots-ui:latest']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - apply
      - '-f'
      - 'deployment.yaml'
      - '--project=$PROJECT_ID'
      - '--location=us-west2-a'
      - '--cluster=group-dots-ui'
