apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-dot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-dot
  template:
    metadata:
      labels:
        app: group-dot
    spec:
      containers:
        - name: group-dot-ui
          image: us-west2-docker.pkg.dev/group-dots/group-dots-ui/group-dots-ui:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: group-dot-ui
spec:
  selector:
    app: group-dot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
